import React from 'react'
import styles from './passwordGeneratorDescription.module.css';
// import styles from './styles.css'
import classNames from 'classnames';
// import cards from './data';

export default () => {
    return (
        <div className="container mt-4">
            <div className="row">
                <div className={`col-md-8 border mb-3 ${styles.main_area}`}>
                    <h2 className='text-start px-3 pt-3 pb-2'>Secure Password Generator for Safe Logins</h2>
                    <p className='px-3 pb-3 text-start'>The motive behind using a strong is to keep it unguessable or un-discoverable.</p>
                    <p className='px-3 py-2 text-start'>A password is used only by the password keeper, and it is up to him whether he wishes to share it with others or want to keep it to himself. The reason why passwords exist is to keep your personal data from being explored by strangers, whenever we sign-up for an account online; the first step it goes for is the verification. This confirmation step includes human validation that a person is creating an account, not a bot and amongst these steps, the websites require secure, hard passwords.</p>
                    <p className='px-3 py-2 text-start'>We, usually keep passwords which are diminishing and are easy to remember. Such passwords include your contact number, date of birth, company name, pet name, school name and everything related to your lifestyle. We prefer keeping short passwords with single case letters which weakens the case, and if your account contains data that is valuable to you, then you’d never go for such an option, you will always need a password with good strength.</p>
                    <p className='px-3 py-2 text-start'>No doubt, if you have more than one accounts, it is difficult to memorize passwords but you can keep all of them safe in a single file, and all you need to remember is just one unique password to that file. It will give you access to all your other accounts, but try not to forget this one because you may get in big trouble.</p>

                    <h3 className='text-start px-3 pt-3 pb-2'>What Makes a Strong Password Generator?</h3>
                    <p className='px-3 pb-3 text-start'>When people keep a passcode they most of the times pulverize the meaning of a robust password. The most used password is (password1), and do you know? When people use hot spots, they often try the most common passcodes first, before asking anyone. Making a password powerful is entirely in your hands; you can let our complex password generator take care of the matter for you. The password generated by this tool is unique, and every password it produces is dissimilar, which means there is no probability of the same password being created again.</p>
                    <p className='px-3 pb-3 text-start'>A strong and complex password contains alphabets, numbers and special characters. The only hard part is to learn special characters which is why it is best to note them down somewhere, memorize them, and delete them.</p>
                    <p className='px-3 pb-3 text-start'>The best use of this secure and unique password generator is when you have to apply a one-time passcode to a file. These types of files are either removed after being downloaded, or the password is changed, you can generate a list of passwords which you can use for this purpose.</p>

                    <h3 className='text-start px-3 pt-3 pb-2'>How Can An Online Password Generator Be Advantageous</h3>
                    <p className=' text-justify px-3 pb-3 text-start'>A complex password can save your account from being cracked if you aren’t aware more than seventeen million passwords were breached in 2017. A <a href=''><b>password generator</b></a> can spawn a password that cannot be broken or guessed, as you know the longer the password, the harder to find the right combination but when you include other characters then it becomes invulnerable. You can efficiently produce a massive list of passwords and save them for later use. OTP (one-time password) can be used if you think someone can find out about your private data.</p>
                    <p className=' text-justify px-3 pb-3 text-start'><b>Did you know:</b> A typical password contains not more than six characters and is kept by people who have weak memories.</p>
                    <p className=' text-justify px-3 pb-3 text-start'>Such passwords can be cracked easily if used a password cracker especially if it is in a single case. Instead of using six you should use a minimum of eight characters and include upper case, lower case letters, and numbers, this type of password is even hard for a supercomputer to crack it will approximately take five years for a supercomputer to break such a password.</p>

                    <h3 className='text-start px-3 pt-3 pb-2'>Can You Manually Create Random Password and Memorize It</h3>
                    <p className='px-3 py-2 text-start'>The passwords generated using an online password generator are a little difficult to memorize. Nine digits that contain symbols, numbers, upper and lower case letters, if you have a good memory, then you can smoothly go for it but still, if there are multiple accounts, then you are not left with any other option but to write them down in some locked folder safely.</p>
                    <p className='px-3 py-2 text-start'>You can generate such passwords manually from the sentences you use every day. A simple sentence like “My name is John, and this is my phone number” can be easily changed to (MniJ+TiMp#). Your every first letter of the sentence can be transformed into a Unique and Complex password, and these are the type of sentences you can never forget, and no one can ever know that a casual sentence can include a complicated password.</p>

                    <h3 className='text-start px-3 pt-3 pb-2'>Changing Passwords Is Important – Create Complex and Strong Password</h3>
                    <p className='px-3 py-2 text-start'>There can be many reasons, but these two are the main ones:</p>
                    <ul className='py-2'>
                        <li className='px-3 py-2 text-start'><b>Forgot to remove old saved passwords</b>
                            <p>If you are upgrading your smartphone make sure to erase all the data from the previous phone. Some of that data can still be restored using various recovery tools, so if you have recently changed your phone or computer but forgot to remove the passcodes to your accounts then make sure to replace them ASAP because who knows what the other person will do when he finds out.</p>
                        </li>
                        <li className='px-3 py-2 text-start'><b>Made your passcode discoverable</b>
                            <p>Your accounts might be at risk if you use the same password for all your accounts. If somebody finds out about this information, then there is a possibility of losing all of your accounts.</p>
                        </li>
                    </ul>

                    <h3 className='text-start px-3 pt-3 pb-2'>How to Create Secure Password With This Tool?</h3>
                    <p className='px-3 py-2 text-start'>Using this tool is entirely trouble-free, all you have to do is walk through the below-given steps, and you will be able to generate a list of strong and Complex passwords in no time:</p>
                    <ol className='py-2'>
                        <li>When you are at the Best Password generator page, you will find a box with a couple of values written in it, which looks like the image down below:</li>
                        <li>In the first option, you have to choose the length of the password (number of characters) which should be at least 8 in order to get the finest good passwords, especially if the account you’re going to use it for contains dominant information.</li>
                        <li>In the selection of the checkboxes you have four different choices, you can keep your password single cased, but it is easily hackable with today’s password crackers. So, we advise you to use all the options or leave just one unchecked and make sure to change your passwords on a routine basis.</li>
                    </ol>

                </div>
            </div>
        </div>
    )
}

